### ISSUE TITLE
rehearser repo?

### ISSUE THREAD

**Issue by cleder** [kevinchwong/rehearser-examples#1]
I cannot view the rehearser repo. Any reason for that?

**Comment by kevinchwong** [comment]
I planned to release rehearser repo source after enough alpha testing, hopefully after next month.

**Comment by kevinchwong** [comment]
Thanks for having interesting in `rehearser`, by the way :)

**Comment by cleder** [comment]
Thanks.
My 2 cents:
Release often, release early (you already do that on pypi, just not on github)
Don't worry, be crappy

It looks like a great addition to https://github.com/cleder/awesome-python-testing
